version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: messages-web-image
    container_name: messages-web-container
    ports:
      - "8000:8000"
      - "4444:4444"
    volumes:
      - "./messages:/usr/src/app/messages"
    stdin_open: true
    tty: true
    depends_on:
      - db
  redis:
    image: redis:7
    container_name: messages-redis-container
    ports:
      - "6379:6379"
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data/"
    environment:
      - "POSTGRES_PASSWORD=a-strong-password"

volumes:
  db_data:
