version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: messages-web-image
    container_name: messages-web-container
    ports:
      - 8000:8000
      - 4444:4444
    volumes:
      - ./messages:/usr/src/app/messages
      - ./data/web:/usr/src/vol/web
    environment:
      - SECRET_KEY=this-is-a-dev-secret-key
      - DEBUG=${DEBUG}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    stdin_open: true
    tty: true
    depends_on:
      - db
  redis:
    image: redis:7
    container_name: messages-redis-container
    ports:
      - 6379:6379
  db:
    image: postgres:15
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  db_data:
