name: Tests CI
on: [push]
env:
  SECRET_KEY: a-strong-secret-key
  DB_NAME: dbname
  DB_USER: dbuser
  DB_PASSWORD: dbpassword
  DB_HOST: 127.0.0.1
jobs:
  Run-CI-Tests:
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        image: postgres
        env:
          POSTGRES_DB: dbname
          POSTGRES_USER: dbuser
          POSTGRES_PASSWORD: dbpassword
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python messages/manage.py test apps
